from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Home Page
    (r'^$', 'lcr.matrix.views.home'),

    # A-Z Files Management
    (r'^az/$', 'lcr.matrix.views.home_az'),
    (r'^az/delete/(\d+)/$', 'lcr.matrix.views.delete_az'),
    (r'^az/download/(\d+)/$', 'lcr.matrix.views.download_az'),

    # IVR Services
    (r'^ivr/live/$', 'lcr.matrix.views.ivr_live'),
    (r'^ivr/cdr/$', 'lcr.matrix.views.ivr_cdr_lastday'),
    (r'^ivr/cdr/(\d+)/(\d+)/$', 'lcr.matrix.views.ivr_cdr'),

    # FS-SBC Hookups (Obsolete, Replaced with SQL Interface)
    (r'^fs/dialplan/', 'lcr.matrix.views.fs_dialplan'),
    (r'^fs/cdr/', 'lcr.matrix.views.fs_cdr'),
    (r'^fs/cdr_test/$', 'lcr.matrix.views.test_cdr'),

    # Charts
    (r'^chart/(\d+)/acd.gif$', 'lcr.matrix.views.chart_acd'),
    (r'^chart/(\d+)/asr.gif$', 'lcr.matrix.views.chart_asr'),
    (r'^chart/(\d+)/min.gif$', 'lcr.matrix.views.chart_min'),
    (r'^chart/switch/(\d+).gif$', 'lcr.matrix.views.chart_switch'),
    (r'^chart/mac/(\d+).gif$', 'lcr.matrix.views.chart_mac'),
    (r'^chart/rr/(\d+)/(\d+).gif$', 'lcr.matrix.views.chart_rr'),
    (r'^chart/stat/(\w+)/(\d+)/', 'lcr.matrix.views.chart_stat'),

    # Retail Ops - Predictive Dialer + Remote Agent Campaigns
    (r'^retail/services/$', 'lcr.matrix.views.retail_services'),
    (r'^retail/edit_service/(\d+)/$', 'lcr.matrix.views.retail_edit_service'),
    (r'^retail/add_service/(\d+)/$', 'lcr.matrix.views.retail_add_service'),
    (r'^retail/destinations/$', 'lcr.matrix.views.retail_destinations'),
    (r'^retail/edit_destination/(\d+)/$', 'lcr.matrix.views.retail_edit_destination'),
    (r'^retail/add_destination/$', 'lcr.matrix.views.retail_add_destination'),
    (r'^retail/add_destination_e164/(\d+)/$', 'lcr.matrix.views.retail_add_destination_e164'),
    (r'^retail/delete_destination_e164/(\d+)/$', 'lcr.matrix.views.retail_delete_destination_e164'),
    (r'^retail/add_service_mod_destination/(\d+)/(\d+)/$', 'lcr.matrix.views.retail_add_service_mod_destination'),
    (r'^retail/del_service_mod_destination/(\d+)/$', 'lcr.matrix.views.retail_del_service_mod_destination'),
    (r'^retail/tariffs/$', 'lcr.matrix.views.retail_tariffs'),
    (r'^retail/edit_tariff/(\d+)/$', 'lcr.matrix.views.retail_edit_tariff'),
    (r'^retail/add_tariff/$', 'lcr.matrix.views.retail_add_tariff'),
    (r'^retail/add_rate/(\d+)/$', 'lcr.matrix.views.retail_add_rate'),
    (r'^retail/del_rate/(\d+)/$', 'lcr.matrix.views.retail_del_rate'),
    (r'^retail/customers/$', 'lcr.matrix.views.retail_customers'),
    (r'^retail/add_customer/$', 'lcr.matrix.views.retail_add_customer'),
    (r'^retail/edit_customer/(\d+)/$', 'lcr.matrix.views.retail_edit_customer'),
    (r'^retail/add_cservice_number/(\d+)/$', 'lcr.matrix.views.retail_add_cservice_number'),
    (r'^retail/del_cservice_number/(\d+)/$', 'lcr.matrix.views.retail_del_cservice_number'),
    (r'^retail/add_cservice/(\d+)/$', 'lcr.matrix.views.retail_add_cservice'),
    (r'^robo01/answer/(\d+)/$', 'lcr.matrix.views.robo01_answer'),
    (r'^robo01/response/(\d+)/(\d+)/$', 'lcr.matrix.views.robo01_response'),
    (r'^robo01/x/$', 'lcr.matrix.views.robo01_x'),
    (r'^register/$', 'lcr.matrix.views.register'),
    (r'^register/(\w+)/$', 'lcr.matrix.views.register_check'),
    (r'^sign/$', 'lcr.matrix.views.register_sign'),
    (r'^ragents/emails/$', 'lcr.matrix.views.ragents_emails'),
    (r'^ragents/queue/$', 'lcr.matrix.views.ragents_queue'),
    (r'^ragents/candidate/(\d+)/$', 'lcr.matrix.views.ragents_candidate'),
    (r'^ragents/list/$', 'lcr.matrix.views.ragents_list'),
    (r'^agent/custadd/(\w+)/(\d+)/$', 'lcr.matrix.views.agent_custadd'),
    (r'^agent/custconf/(\d+)/$', 'lcr.matrix.views.agent_custconf'),
    (r'^agent/call/(.*?)/(\d+)/$', 'lcr.matrix.views.agent_call'),
    (r'^agent/script/(\w+)/$', 'lcr.matrix.views.agent_script'),
    (r'^agent/training/$', 'lcr.matrix.views.agent_training'),
    (r'^agent/leads/$', 'lcr.matrix.views.agent_leads'),
    (r'^agent/help/$', 'lcr.matrix.views.agent_help'),
    (r'^agent/faq/$', 'lcr.matrix.views.agent_faq'),
    (r'^agent/materials/$', 'lcr.matrix.views.agent_materials'),
    (r'^agent/status/$', 'lcr.matrix.views.agent_status'),
    (r'^agent/pause/$', 'lcr.matrix.views.agent_pause'),
    (r'^agent/unpause/$', 'lcr.matrix.views.agent_unpause'),
    (r'^agent/cbadd/$', 'lcr.matrix.views.agent_cbadd'),

    # Wholesale Ops - Switching, Billing, Reconciliation, CDR Tools
    (r'^add_recon/$', 'lcr.matrix.views.add_recon'),
    (r'^res_recon/(\d+)/$', 'lcr.matrix.views.res_recon'),
    (r'^csv_recon/(\d+)-(\w+).csv$', 'lcr.matrix.views.rr_csv'),
    (r'^ver_stats/$', 'lcr.matrix.views.ver_stats'),
    (r'^edit_escalation/(\d+)/$', 'lcr.matrix.views.edit_escalation'),
    (r'^dashboard/$', 'lcr.matrix.views.dashboard'),
    (r'^dax/$', 'lcr.matrix.views.dax'),
    (r'^ajx_dax_stats/(\d+)/(\d+)/$', 'lcr.matrix.views.ajx_dax_stats'),
    (r'^json/switch/(\d+)/(\d+).json$', 'lcr.matrix.views.json_switch'),
    (r'^view_billing/$', 'lcr.matrix.views.view_billing'),
    (r'^server_monitor/$', 'lcr.matrix.views.server_monitor'),
    (r'^list_carriers/$', 'lcr.matrix.views.list_carriers'),
    (r'^edit_carrier/(\d+?)/$', 'lcr.matrix.views.edit_carrier'),
    (r'^edit_customer/(\d+?)/$', 'lcr.matrix.views.edit_customer'),
    (r'^add_customer_ip/(\d+?)/$', 'lcr.matrix.views.add_customer_ip'),
    (r'^del_customer_ip/(\d+?)/$', 'lcr.matrix.views.del_customer_ip'),
    (r'^add_carrier_customer/(\d+?)/$', 'lcr.matrix.views.add_carrier_customer'),
    (r'^add_carrier_supplier/(\d+?)/$', 'lcr.matrix.views.add_carrier_supplier'),
    (r'^stats/$', 'lcr.matrix.views.stats'),
    (r'^switch_stats/$', 'lcr.matrix.views.switch_stats'),
    (r'^upload/$', 'lcr.matrix.views.uploadAZ'),
    (r'^supplier/$', 'lcr.matrix.views.supplier'),
    (r'^usupplier/$', 'lcr.matrix.views.usupplier'),
    (r'^test_routes/$', 'lcr.matrix.views.test_routes'),
    (r'^add_route/$', 'lcr.matrix.views.add_route'),
    (r'^add_test/$', 'lcr.matrix.views.add_test'),
    (r'^add_deal/$', 'lcr.matrix.views.add_deal'),
    (r'^list_monitors/$', 'lcr.matrix.views.list_monitors'),
    (r'^monitor_reset/(\d+)/$', 'lcr.matrix.views.monitor_reset'),
    (r'^monitor_delete/(\d+)/$', 'lcr.matrix.views.monitor_delete'),
    (r'^monitor_edit/(\d+)/$', 'lcr.matrix.views.monitor_edit'),
    (r'^add_monitor/$', 'lcr.matrix.views.add_monitor'),
    (r'^add_point/$', 'lcr.matrix.views.add_point'),
    (r'^dest_add/$', 'lcr.matrix.views.dest_add'),
    (r'^dest_list/$', 'lcr.matrix.views.dest_list'),
    (r'^dest_details/(\d+)/$', 'lcr.matrix.views.dest_details'),
    (r'^dest_add_e164/(\d+)/$', 'lcr.matrix.views.dest_add_e164'),
    (r'^dest_del_e164/(\d+)/$', 'lcr.matrix.views.dest_del_e164'),
    (r'^view_deal/$', 'lcr.matrix.views.view_deal'),
    (r'^edit_deal/(\d+)/$', 'lcr.matrix.views.edit_deal'),
    (r'^add_code/(\d+)/$', 'lcr.matrix.views.add_code'),
    (r'^delete_code/(\d+)/$', 'lcr.matrix.views.delete_code'),
    (r'^invoice/add/(\d+)/$', 'lcr.matrix.views.invoice_add'),
    (r'^invoice/edit/(\d+)/$', 'lcr.matrix.views.invoice_edit'),
    (r'^invoice/pdf/(\d+)/$', 'lcr.matrix.views.invoice_pdf'),
    (r'^invoice/delete/(\d+)/$', 'lcr.matrix.views.invoice_delete'),
    (r'^ajx_invoice/(\d+)/available_deals/$', 'lcr.matrix.views.ajx_invoice_available_deals'),
    (r'^ajx_invoice/(\d+)/add_deal/(\d+)/$', 'lcr.matrix.views.ajx_invoice_add_deal'),
    (r'^ajx_invoice/(\d+)/details/$', 'lcr.matrix.views.ajx_invoice_details'),
    (r'^ajx_invoice/rem_pos/(\d+)/$', 'lcr.matrix.views.ajx_invoice_rem_pos'),
    (r'^ajx_invoice/edit_pos/(\d+)/(\d+)/$', 'lcr.matrix.views.ajx_invoice_edit_pos'),
    (r'^ajx_invoice/edit_tax/(\d+)/(\d+)/$', 'lcr.matrix.views.ajx_invoice_edit_tax'),
    (r'^ajx_invoices/(\d+)/(\d+)/$', 'lcr.matrix.views.ajx_invoices_month'),
    (r'^bill/month/$', 'lcr.matrix.views.bill_month'),
    (r'^live_calls/$', 'lcr.matrix.views.live_calls'),
    (r'^view_test/(\d+)/$', 'lcr.matrix.views.view_test'),
    (r'^bank_index/$', 'lcr.matrix.views.bank_index'),
    (r'^ems_index/$', 'lcr.matrix.views.ems_index'),
    (r'^ajx_ac_code', 'lcr.matrix.views.ajx_ac_code'),
    (r'^ajx_sc_code', 'lcr.matrix.views.ajx_sc_code'),
    (r'^ajx_rc_term', 'lcr.matrix.views.ajx_rc_term'),
    (r'^ajx_ag_data', 'lcr.matrix.views.ajx_ag_data'),
    (r'^ajx_ag_ver', 'lcr.matrix.views.ajx_ag_ver'),
    (r'^ajx_ag_ass', 'lcr.matrix.views.ajx_ag_ass'),
    (r'^ajx_deal/(\d+)/$', 'lcr.matrix.views.ajx_deal'),
    (r'^ajax/dd/(\d+)/$', 'lcr.matrix.views.ajax_dd'),
    (r'^ajax/mera/calls/$', 'lcr.matrix.views.ajax_mera_calls'),
    (r'^mvts/calls/$', 'lcr.matrix.views.mvts_calls'),
    (r'^mvts/report/$', 'lcr.matrix.views.mvts_report'),
    (r'^mvts/alert/$', 'lcr.matrix.views.mvts_alert'),
    (r'^cdrgen/index/$', 'lcr.matrix.views.cdrgen_index'),
    (r'^email/index/$', 'lcr.matrix.views.email_index'),

    # Carrier Website
    (r'^carrier/register/$', 'lcr.matrix.views.carrier_register'),
    (r'^carrier/escalation/$', 'lcr.matrix.views.carrier_escalation'),
    (r'^carrier/contact/$', 'lcr.matrix.views.carrier_contact'),
    (r'^carrier/deals/$', 'lcr.matrix.views.carrier_deals'),
    (r'^carrier/deal_details/(\d+)/', 'lcr.matrix.views.carrier_deal_details'),

    # Public Tools
    (r'^free/cdrgen/', 'lcr.matrix.views.free_cdrgen'),

    # Generic URLs
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/lcr/public_html/lcr/media'}),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)
